### PR TITLE
mm_jobman.sh: Added download options to include and recursive

### PR DESCRIPTION
**Pull request by Ashley-Tung**
Each `--download-include` will correspond to their respective `--download` (first `--download-include` will be for the first `--download`, etc).  It is up to the user to make sure their parameters are correct and to make note of this respective matching. Same will go with `--recursive`

For example, if my parameters are (does not have to be in this order)
```
--download remote1:local1 --recursive true --download-include '*.txt *.bim' \
--download remote2:local2 --download-include '*.csv' 
```
then my download commands will be
```
aws s3 cp remote1 local1 --recursive --include '*.txt' --include '*.bim'
aws s3 cp remote2 local2 --include '*.csv'
```

### CODE REVIEW

**Comment by gaow** [comment]
@Bale4  please use this to compose our new command then we can test. If it works let's merge it

**Comment by rfeng2023** [comment]
@Ashley-Tung sorry, I made the mistake of merging this PR before the test was successful.

I found that you did not add `--download-include` in your real `download_cmd`, which would lead an error in job `euaoysqhyg7k7m4be3wr7`
```
mkdir: unrecognized option '--download-include'
Try 'mkdir --help' for more information.
```
 I may need to revert this PR back, and could you please help to test the submission command first and then submit a new PR?

the submission command should be 
```bash
username=aw3600
./src/mm_jobman.sh \
 ./example/commands_to_submit.txt \
 -c 2 -m 16 \
 --job-size 100 \
 --mount statfungen/ftp_fgc_xqtl:/home/$username/data \
	 statfungen/ftp_fgc_xqtl/sos_cache/$username:/home/$username/.sos \
 --mountOpt "mode=r" "mode=rw"  \
 --cwd "/home/$username/data" \
 --image ghcr.io/cumc/pecotmr_docker:latest \
 --entrypoint "source /usr/local/bin/_activate_current_env.sh" \
 --env ENV_NAME=pecotmr \
 --imageVolSize 10 \
 --opcenter 54.81.85.209 \
 --download "statfungen/ftp_fgc_xqtl/ROSMAP/genotype/geno_by_chrom/:/home/$username/input --download-include 'ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.*' "  \
 --upload /home/$username/output:statfungen/ftp_fgc_xqtl/ \
 --no-fail-fast \
 --volMount "60:/home/$username/input"
```
and the content in ` ./example/commands_to_submit.txt` should be 
```
sos run xqtl-pipeline/pipeline/cis_workhorse.ipynb susie_twas --name Mic_example --genoFile ../input/ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bed --phenoFile eQTL/ROSMAP/DLPFC_Mic/analysis_ready/phenotype_preprocessing/Mic.log2cpm.region_list.txt --covFile eQTL/ROSMAP/DLPFC_Mic/analysis_ready/covariate_preprocessing/Mic.log2cpm.Mic.rosmap_cov.ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.snuc_pseudo_bulk.related.plink_qc.extracted.pca.projected.Marchenko_PC.gz --phenotype-names Mic --customized-cis-windows fungen-xqtl-analysis/resource/TADB_enhanced_cis.bed --cwd ../output/ --region-name ENSG00000158869 --no-indel
sos run xqtl-pipeline/pipeline/cis_workhorse.ipynb susie_twas --name Mic_example --genoFile ../input/ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bed --phenoFile eQTL/ROSMAP/DLPFC_Mic/analysis_ready/phenotype_preprocessing/Mic.log2cpm.region_list.txt --covFile eQTL/ROSMAP/DLPFC_Mic/analysis_ready/covariate_preprocessing/Mic.log2cpm.Mic.rosmap_cov.ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.snuc_pseudo_bulk.related.plink_qc.extracted.pca.projected.Marchenko_PC.gz --phenotype-names Mic --customized-cis-windows fungen-xqtl-analysis/resource/TADB_enhanced_cis.bed --cwd ../output/ --region-name ENSG00000188157 --no-indel
```

**Comment by Ashley-Tung** [comment]
Hi @gaow, I am a little confused by what you mean by "you did not add --download-include in your real download_cmd". 

However, if I were to dryrun your command, this is one of the generated scripts, there seems to be a bug in which the whole `--download-command` gets added to the `mkdir` part:
```
# Create directories if they don't exist for download
mkdir -p /home/aw3600/input --download-include 'ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.*'
# Create directories if they don't exist for upload
mkdir -p /home/aw3600/output
# Create directories if they don't exist for cwd
mkdir -p /home/aw3600/data

# Execute the download commands to fetch data from S3
aws s3 cp s3://statfungen/ftp_fgc_xqtl/ROSMAP/genotype/geno_by_chrom/ /home/aw3600/input --download-include 'ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.*'
```

However, I believe what happened was you gave your `--download` and `--download-include` commands like this:
```
--download "statfungen/ftp_fgc_xqtl/ROSMAP/genotype/geno_by_chrom/:/home/$username/input --download-include 'ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.*'"
```

Which makes the script think that `--download-include` is part of the `--download` command

Provide the parameters like below, without the encasing quotation marks:
```
--download "statfungen/ftp_fgc_xqtl/ROSMAP/genotype/geno_by_chrom/:/home/$username/input" \
 --download-include 'ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.*'
```

And your script will look like this:
```
#!/bin/bash

set -o errexit -o pipefail
# Activate environment with entrypoint in job script
source /usr/local/bin/_activate_current_env.sh

# Create directories if they don't exist for download
mkdir -p /home/aw3600/input
# Create directories if they don't exist for upload
mkdir -p /home/aw3600/output
# Create directories if they don't exist for cwd
mkdir -p /home/aw3600/data

# Execute the download commands to fetch data from S3
aws s3 cp s3://statfungen/ftp_fgc_xqtl/ROSMAP/genotype/geno_by_chrom/ /home/aw3600/input --include ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.*

# Change to the specified working directory
cd /home/aw3600/data

# Initialize a flag to track command success
# which can be changed in || true
command_failed=0
{
    while IFS= read -r command; do
        eval $command || true
    done <<< '''parallel ::: "sos run xqtl-pipeline/pipeline/cis_workhorse.ipynb susie_twas --name Mic_example --genoFile ../input/ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bed --phenoFile eQTL/ROSMAP/DLPFC_Mic/analysis_ready/phenotype_preprocessing/Mic.log2cpm.region_list.txt --covFile eQTL/ROSMAP/DLPFC_Mic/analysis_ready/covariate_preprocessing/Mic.log2cpm.Mic.rosmap_cov.ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.snuc_pseudo_bulk.related.plink_qc.extracted.pca.projected.Marchenko_PC.gz --phenotype-names Mic --customized-cis-windows fungen-xqtl-analysis/resource/TADB_enhanced_cis.bed --cwd ../output/ --region-name ENSG00000158869 --no-indel" "sos run xqtl-pipeline/pipeline/cis_workhorse.ipynb susie_twas --name Mic_example --genoFile ../input/ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bed --phenoFile eQTL/ROSMAP/DLPFC_Mic/analysis_ready/phenotype_preprocessing/Mic.log2cpm.region_list.txt --covFile eQTL/ROSMAP/DLPFC_Mic/analysis_ready/covariate_preprocessing/Mic.log2cpm.Mic.rosmap_cov.ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.snuc_pseudo_bulk.related.plink_qc.extracted.pca.projected.Marchenko_PC.gz --phenotype-names Mic --customized-cis-windows fungen-xqtl-analysis/resource/TADB_enhanced_cis.bed --cwd ../output/ --region-name ENSG00000188157 --no-indel"'''
}

# Always execute the upload commands to upload data to S3
aws s3 sync /home/aw3600/output s3://statfungen/ftp_fgc_xqtl//output

# Check if any command failed
if [ $command_failed -eq 1 ]; then
    exit 1
fi

```

**Comment by rfeng2023** [comment]
@Ashley-Tung error showing "fatal error: An error occurred (404) when calling the HeadObject operation: Key "ftp_fgc_xqtl/ROSMAP/genotype/geno_by_chrom/" does not exist" with submission command:

```bash
username=aw3600
./src/mm_jobman.sh \
 ./example/commands_to_submit.txt \
 -c 2 -m 16 \
 --job-size 100 \
 --mount statfungen/ftp_fgc_xqtl:/home/$username/data \
	 statfungen/ftp_fgc_xqtl/sos_cache/$username:/home/$username/.sos \
 --mountOpt "mode=r" "mode=rw"  \
 --cwd "/home/$username/data" \
 --image ghcr.io/cumc/pecotmr_docker:latest \
 --entrypoint "source /usr/local/bin/_activate_current_env.sh" \
 --env ENV_NAME=pecotmr \
 --imageVolSize 10 \
 --opcenter 54.81.85.209 \
 --download "statfungen/ftp_fgc_xqtl/ROSMAP/genotype/geno_by_chrom/:/home/$username/input" \
 --download-include 'ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.*'  \
 --upload /home/$username/output:statfungen/ftp_fgc_xqtl/ \
 --no-fail-fast \
 --volMount "60:/home/$username/input"
```

**Comment by rfeng2023** [comment]
@Ashley-Tung could you please take a look at the above submission commands and ` ./example/commands_to_submit.txt `, could you please also test them, and correct them if there is any problem and then submit a new PR?

**Comment by Ashley-Tung** [comment]
Hi @gaow  I would not be able to test properly unless I have access to your bucket. 

Your download command is `aws s3 cp s3://statfungen/ftp_fgc_xqtl/ROSMAP/genotype/geno_by_chrom/ /home/aw3600/input --include ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.*`

First, looking at your error, does `ftp_fgc_xqtl/ROSMAP/genotype/geno_by_chrom` exist in your bucket?

If it does, I am assuming your `ROSMAP*` files are in the `geno_by_chrom` folder.  If that is the case, you will need `--recursive` because you are **recursively** looking for files that match that pattern, not directly copying a singular file. Hence the `/` at the end of `s3://statfungen/ftp_fgc_xqtl/ROSMAP/genotype/geno_by_chrom/ `.

This is local example below. See that I want to cp my `execution*` files to my `test` folder. I end in an error.
```
[ec2-user@ip-172-31-27-61 ~]$ aws s3 cp s3://jfs-spotonly/pipeline_info/ /home/ec2-user/test --include execution*
download failed: s3://jfs-spotonly/pipeline_info/ to test/ [Errno 20] Not a directory: '/home/ec2-user/test/.a6F07255' -> '/home/ec2-user/test/'
```

With recursive:
```
[ec2-user@ip-172-31-27-61 ~]$ aws s3 cp s3://jfs-spotonly/pipeline_info/ /home/ec2-user/test --include execution* --recursive
download: s3://jfs-spotonly/pipeline_info/pipeline_dag_2023-10-24_22-13-22.html to /home/ec2-user/test/pipeline_dag_2023-10-24_22-13-22.html
download: s3://jfs-spotonly/pipeline_info/execution_trace_2023-10-24_22-13-22.txt to /home/ec2-user/test/execution_trace_2023-10-24_22-13-22.txt
download: s3://jfs-spotonly/pipeline_info/execution_timeline_2023-10-24_22-13-22.html to /home/ec2-user/test/execution_timeline_2023-10-24_22-13-22.html
download: s3://jfs-spotonly/pipeline_info/execution_report_2023-10-24_22-13-22.html to /home/ec2-user/test/execution_report_2023-10-24_22-13-22.html
```

Please retry with `--recursive true`

**Comment by Ashley-Tung** [comment]
I can submit a PR to add the `--recursive true` to the README

**Pull request merged**
